// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFVEepgnUQDzDLtEeNX74QwNwrg5mr_Mo',
    appId: '1:430337420930:web:3ed0e39088ad7637e44e9b',
    messagingSenderId: '430337420930',
    projectId: 'blackcoffer-b390c',
    authDomain: 'blackcoffer-b390c.firebaseapp.com',
    storageBucket: 'blackcoffer-b390c.appspot.com',
    measurementId: 'G-F2KMXVET7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTL960flxxgAq3rqCmAk4Kf96YCa9dKc',
    appId: '1:430337420930:android:26770599905389dde44e9b',
    messagingSenderId: '430337420930',
    projectId: 'blackcoffer-b390c',
    storageBucket: 'blackcoffer-b390c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9MZuZaDgLosin7jQrufoEMyxHgI9Iav0',
    appId: '1:430337420930:ios:35b7db4a4faab81de44e9b',
    messagingSenderId: '430337420930',
    projectId: 'blackcoffer-b390c',
    storageBucket: 'blackcoffer-b390c.appspot.com',
    iosBundleId: 'com.example.demoappblackcoffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9MZuZaDgLosin7jQrufoEMyxHgI9Iav0',
    appId: '1:430337420930:ios:e62512a53803edfee44e9b',
    messagingSenderId: '430337420930',
    projectId: 'blackcoffer-b390c',
    storageBucket: 'blackcoffer-b390c.appspot.com',
    iosBundleId: 'com.example.demoappblackcoffer.RunnerTests',
  );
}
